.\" This man page is a concise summary of Trackballs. Full documentation for the game and the editor can be found in the documentation provided with the source code or at https://trackballs.github.io/docs/index.html.
.TH "trackballs" "6" "2018-04-02" "Mathias Broxvall" "Games"
.SH "NAME"
Trackballs \- marble game similar to the classic arcade game 'Marble Madness'
.SH "SYNOPSIS"
.B trackballs\fP [\fB\-w\fP] [\fB\-m\fP] [\fB\-y\fP] [\fB\-f\fP] [\fB\-e\fP \fB\-l\fP<level> \fB\-t\fP<level>] [\fB\-r\fP<width>] [\fB-s\fP<sensitivity>] ...

.SH "DESCRIPTION"

Trackballs is a simple game inspired by the classic Atari 1980's arcade game 'Marble Madness' (later released by Electronic Arts for the Amiga and other platforms).

By steering a marble ball through a labyrinth filled with sharp objects, pools of acid and other obstacles the player collects points. When the ball passes through the goal it continues to the next, more difficult track \- unless the time runs out.

It should be noted that this game is _not_ intended to be a replica of Marble Madness but rather merely inspired by it. For instance the game uses 3D graphics even though the original game had no real use for it. Also the game is fully programmable with a scripting extension (Guile), and includes a level editor with which to easily create new levels.

.SH "OPTIONS"
.TP
.BI \-h\ \fR,\ \fB\-\-help
Display usage information.
.TP
.BI \-l\ \fR,\ \fB\-\-level
Start from level.
.TP
.BI \-w\ \fR,\ \fB\-\-windowed
Run in window (Default is fullscreen)
.TP
.BI \-m\ \fR,\ \fB\-\-mute
 Mute sound.
.TP
.BI \-y\ \fR,\ \fB\-\-low-memory
Attempt to conserve memory usage
.TP
.BI \-s\ \fR,\ \fB\-\-sensitivity
Mouse sensitivity, default 1.0
.TP
.BI \-f\ \fR,\ \fB\-\-fps
Displays framerate
.TP
.BI \-v\ \fR,\ \fB\-\-version
Indicate the current version number
.TP
.BI \-9\ \fR,\ \fB\-\-debug\-joystick
Debug joystick status
.TP
.BI \-j\ \fR,\ \fB\-\-repair\-joystick
Correct for bad joysticks
.TP
.BI \-t\ \fR,\ \fB\-\-touch
Updates a map to the latest format

.SH "ENVIRONMENT"
.LP
.TP
\fBGUILE_LOAD_PATH\fP
Specifies the directory where the guile files are
.TP
\fBTRACKBALLS\fP
Specifies a preferred share directory; this is ignored if invalid

.SH "FILES"
.LP
.TP
${TRACKBALLS_BIN}/trackballs
The executable file for trackballs
.TP
${TRACKBALLS_SHARE}
Necessary shared files for trackballs
.TP
${TRACKBALLS_LOCALE}
Location of the locale files, if applicable
.TP
${TRACKBALLS_DOC}
Detailed package documentation
.TP
~/.trackballs/
Per user settings directory

.SH "EXAMPLE"
.LP
To run this program the standard way type:
.LP
    trackballs
.LP
To disable audio and start in windowed mode
.LP
    trackballs \-m -w
.LP
Alternatively you can test a level with:
.LP
    trackballs \-l steep

.SH "NOTES"
.LP
Full documentation for the game and the editor can be found in the detailed package documentation or at
.UR https://trackballs.github.io/docs/index.html
.UE

.SH "AUTHORS"
.LP
See the AUTHORS.md file in the source package for a detailed list of authors.


